---
abstract: ~
author:
  - 'Carl Franks, C<cfranks@cpan.org>'
build_requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::View::TT: 0
  Template: 0
  Test::WWW::Mechanize: 1.16
  Test::WWW::Mechanize::Catalyst: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Controller-HTML-FormFu
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Component::InstancePerContext: 0
  Catalyst::Runtime: 5.70
  Config::Any: 0
  File::Spec: 0
  HTML::FormFu: 0.03000
  NEXT: 0
  Regexp::Assemble: 0
  Scalar::Util: 0
  Task::Weaken: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.03004
