--- 
abstract: ~
author: Carl Franks, C<cfranks@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Controller-HTML-FormFu
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst::Runtime: 0
  Config::Any: 0
  File::Spec: 0
  HTML::FormFu: 0
  NEXT: 0
  Scalar::Util: 0
version: 0.01001
