---
abstract: 'Catalyst integration for HTML::FormFu'
author:
  - 'Carl Franks, C<cfranks@cpan.org>'
build_requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Plugin::ConfigLoader: 0.23
  Catalyst::Plugin::Session: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::File: 0
  Catalyst::View::TT: 0
  Config::General: 0
  ExtUtils::MakeMaker: 6.42
  Template: 0
  Test::More: 0.92
  Test::WWW::Mechanize: 1.16
  Test::WWW::Mechanize::Catalyst: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Controller-HTML-FormFu
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Component::InstancePerContext: 0
  Catalyst::Runtime: 5.71001
  Config::Any: 0
  File::Spec: 0
  HTML::FormFu: 0.04001
  MRO::Compat: 0.10
  Moose: 0
  MooseX::ChainedAccessors: 0.02
  Regexp::Assemble: 0
  Scalar::Util: 0
  Task::Weaken: 0
  namespace::autoclean: 0
resources:
  bugtracker: https://github.com/fireartist/Catalyst-Controller-HTML-FormFu/issues
  license: http://dev.perl.org/licenses/
  repository: git://github.com/fireartist/Catalyst-Controller-HTML-FormFu.git
version: 0.09002
